### ISSUE TITLE
Action Items - Meeting #2 (24 Jan)

### ISSUE THREAD

**Issue by joehand** [datprotocol/working-group#3]
### Action items
Dat Protocol WG meeting 24 Jan 2018 ([meeting notes](https://github.com/datprotocol/working-group/blob/master/meeting-notes/02-24jan2018.md))

* Working Group Meta Info
    - [x] datprotocol/working-group Repo Updates
        - [x] Record active members (@joehand)
        - [x] Document WG member add/remove process (@joehand)
        - [x] Issue template for adding new WG members (@joehand)
        - [x] Add link/info about integration tests (@joehand)
    - [ ] Datprotocol.com
        - [ ] **(BLOCKER)** DEP-001 Merged
        - [ ] Autogeneration of DEPs for display
        - [ ] Merge PR https://github.com/datprotocol/website/pull/6
* DEPs
    * DEP-0001
        - [x] Edit and submit based on meeting decisions (@bnewbold)
        - [ ] Review PR before next meeting (WG)
    * Upcoming DEPs 
        * High Priority - *Prepare Drafts*
            - [ ] wire-protocol - *standard* (@pfrazee, @mafintosh review)
            - [ ] hyperdb - *standard* (@bnewbold, @mafintosh review)
            - [ ] multi-writer - *standard* (@bnewbold, @mafintosh review)
            - [ ] nomenclature - *informative* (@joehand, WG review)
        * Lower Priority (already in paper)
            - [ ] discovery - *informative* (@taravancil/@pfrazee, @mafintosh review)
            - [ ] hypercore|drive - *standard* (@pfrazee, @mafintosh review)
            - [ ] SLEEP - *standard* 
* Other
    * Network Uptime Improvements
        - [ ] IA host DNS server (@bnewbold ping maf about it)
        - [ ] Prototype DNS -> Hyperdht
* Next Meeting (Feb 7, 9:30am PST)
    - [x] Setup issue for agenda (@joehand)
        - [x] Add multi-writer concerns we punted (@joehand)
    - [ ] Make template for notes (@joehand)
    - [ ] Make recurring calendar invites (@joehand)

**Comment by bnewbold** [comment]
@joehand (and @mafintosh) some specific nomenclature ambiguities I can think of:

- when discussing the concept of a single "hyperlog register" (aka, an append only log with a specific public key; a Dat archive is made up of two of these), is it called: "a hyperlog"? "a hypercore"? register, log, feed?
- within a dat protocol connection, there can be multiple hyperlog registers synchronized. These each get a channel ID, to disambiguate which messages are about which register. Terms "channel", "feed", "register" are redundant in that context (aka, all refer to the same thing); channel isn't great because it could be referring to a connection at almost any abstraction layer?
- when two hypercore peers connect they can do all sorts of things. do we refer to all of these vaguely as "synchronizing"? "being a member of the swarm"? the later isn't great because it might just be a persistent 1-to-1 connection. Could involve uploading and/or downloading. Maybe just "connected"?
- what are the "entries" within a single hyperlog called, and their number? "version", "entry", "chunk", "element", "node", "id", "index". How to disambiguate between talking about a hyperlog "entry" and a member of a SLEEP file? In the sleep context "entry", "element", and "chunk" also make sense.

I don't think these need to be all worked out for other technical DEPs to get merged as Draft, but they should probably be clarified before we set anything in stone. I also get hung up coding or talking about these all the time because i'm not sure what word to use when (I don't think there is a correct answer yet).
